name: Auto Update Scores

on:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours
  workflow_dispatch: # Enable manual trigger

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Sync Scores
        run: node scripts/sync-ncaa.js
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
